" Basic configuration
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set backspace=indent,eol,start
set nobackup
set number
set hlsearch
set incsearch
set mouse=a
set cursorline

" gVim configuration
if has("gui_running")
    set guifont="Sarasa Mono SC 14"
endif

" Plugins
call plug#begin('~/.vim/plugged')
    " Color schemes
    Plug 'altercation/vim-colors-solarized'
    " Plug 'endel/vim-github-colorscheme'
    " Plug 'dracula/vim', { 'as': 'colors-dracula' }

    " vim-airline
    Plug 'vim-airline/vim-airline'
    Plug 'vim-airline/vim-airline-themes'
call plug#end()

" Syntax and color scheme
syntax on
filetype plugin indent on
set background=dark
let g:solarized_termcolors=256
colorscheme solarized
" highlight CursorLine cterm=bold

" vim-airline
if match($TERM, "xterm") == 0 || $TERM == "tmux-256color" || has("gui_running")
    let g:airline_powerline_fonts = 1
    let g:airline_theme = 'dark'
    set laststatus=2
endif
